services:
  database-postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./PostgreSQL/Init.Development.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - services

  foxstevenle-api:
    image: foxstevenle-api
    build:
      context: .
      dockerfile: FoxStevenle.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Development
    ports:
      - '5200:5200'
    volumes:
      - ../hints:/hints
    depends_on:
      - database-postgresql
    networks:
      - services
    environment:
      ASPNETCORE_ENVIRONMENT: Development

networks:
  services:

volumes:
  postgres: